/**
 * The starter deck `nh-deck init` writes for a brand-new user -- Marp
 * (nh-deck's closest sibling tool) ships no equivalent scaffolding command
 * at all, so this is a genuine differentiator, not table-stakes parity.
 *
 * Deliberately a NEW, distinct deck from `fixtures/sample.md` (the fixture
 * `render.test.ts`/`cli.test.ts` already depend on) rather than a copy of
 * it -- the two serve different audiences (an internal test fixture vs. a
 * first-run scaffold a real user reads and edits) and must stay free to
 * diverge without one change silently breaking the other's tests.
 *
 * Doubles as living, in-deck documentation: it exercises real frontmatter
 * (`theme:`/`transition:`), one slide per fixed layout (`title`/`section`/
 * `two-column`/`quote`, via the existing `<!-- layout: name -->` marker),
 * one KaTeX example (inline and block math), one Mermaid diagram, one
 * presenter-note comment, and a closing slide that literally spells out the
 * presentation-mode keyboard shortcuts and the `?present`/`?notes` query
 * params as slide CONTENT -- today there is no other in-deck way to
 * discover either of those. The closing slide's shortcut list is kept
 * word-for-word in sync with `presentationScript.ts`'s own in-app help
 * overlay text (its "Navigate"/"View" `<dl>`), so this scaffold can never
 * silently drift out of date with what pressing "?" while presenting
 * actually shows.
 *
 * Built as a plain array of lines joined with "\n" (mirroring
 * `tests/cli.test.ts`'s own `combinedMarkdown` fixture convention) rather
 * than a single template literal, so the Markdown body's own liberal use of
 * backticks (inline code spans, a fenced ```mermaid block) never has to be
 * escaped against this file's own string-literal delimiters.
 */
export const DEFAULT_INIT_FILENAME = "deck.md";

export const STARTER_DECK_TEMPLATE = [
	"---",
	"theme: dracula",
	"transition: fade",
	"---",
	"<!-- layout: title -->",
	"",
	"# Welcome to nh-deck",
	"",
	"A starter deck to help you get going -- everything below is a real, working example you can edit, extend, or delete.",
	"",
	"---",
	"",
	"<!-- layout: section -->",
	"",
	"## Getting Started",
	"",
	"This deck was generated by `nh-deck init`. Keep it open as a reference while you build your own, or delete it entirely.",
	"",
	"---",
	"",
	"<!-- layout: two-column -->",
	"",
	"## What This Deck Covers",
	"",
	"- The `title`, `section`, `two-column`, and `quote` layouts",
	"- Inline and block math with KaTeX",
	"- A Mermaid diagram",
	"- Presenter notes",
	"- Presentation-mode keyboard shortcuts",
	"",
	"Everything above is opt-in -- a deck with no layout markers, theme, or transition renders exactly as plain Markdown always has.",
	"",
	"---",
	"",
	"<!-- layout: quote -->",
	"",
	"Simplicity is the ultimate sophistication.",
	"",
	"Leonardo da Vinci",
	"",
	"---",
	"",
	"## Math with KaTeX",
	"",
	"nh-deck renders inline math like $E = mc^2$ right in a sentence, and block equations on their own line:",
	"",
	"$$",
	"\\sum_{i=1}^{n} i = \\frac{n(n+1)}{2}",
	"$$",
	"",
	"No layout marker needed here -- math rendering works on every slide.",
	"",
	"---",
	"",
	"## Diagrams with Mermaid",
	"",
	"Fenced `mermaid` code blocks render as embedded, CDN-free SVG:",
	"",
	"```mermaid",
	"flowchart LR",
	"  Write[Write Markdown] --> Render[nh-deck render]",
	"  Render --> Present[Present or export]",
	"```",
	"",
	"---",
	"",
	"## Presenter Notes",
	"",
	"Add a standalone HTML comment to any slide to leave yourself a note -- it never renders as visible slide content.",
	"",
	"<!-- Remember: presenter notes stay hidden until ?notes is added to the URL. -->",
	"",
	"Reveal every note on the page at once by adding `?notes` to this deck's served URL.",
	"",
	"---",
	"",
	"## Presenting This Deck",
	"",
	"Add `?present` to this deck's served URL for one-slide-at-a-time presentation mode, with a slide counter and progress bar. Add `?notes` to reveal every presenter note on the page at once.",
	"",
	"Once presenting, press `?` any time to see this again:",
	"",
	"- **Navigate:** → / Space / ← / Home / End / click / swipe, `G` + digits + Enter — jump to slide",
	"- **View:** `O` — overview, `P` — presenter view, `?` — this help, `Esc` — exit or close",
	"",
	"Delete this deck and start your own, or keep building on it -- happy presenting!",
	"",
].join("\n");
